# thymeleaf
spring:
  # static
  resources:
    add-mappings: true
    chain:
      cache: true
      gzipped: true
      html-application-cache: true
    static-locations: classpath:/static/
    cache:
      cachecontrol:
        max-age: 3600
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    # druid
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据库连接池属性
    # 统计状态
    filters: stat
    # 最大活动连接
    maxActive: 1000
    # 初始连接池大小
    initialSize: 100
    # 最大等待时间
    maxWait: 60000
    # 最小的空闲连接
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # rabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        # 每次从队列中取几个
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
        # 队列满了重试
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          # 每次等待倍数
          multiplier: 1.0

# redis
redis:
  host: localhost
  port: 6379
  timeout: 3
  # 连接池属性
  poolMaxTotal: 1000
  poolMaxIdle: 100
  poolMaxWait: 500


# mybatis
mybatis:
  type-aliases-package: com.todorex.miaosha.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/todorex/miaosha/dao/*.xml




